spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

  datasource:
#    url: jdbc:h2:file:f:/temp/testdb;MODE=MYSQL
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  redis:
    database: 0
    host: 192.168.11.8
    port: 6379
    connect-timeout: 5000
  cache:
    redis:
      time-to-live: 1d
      use-key-prefix: true

#mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
secure:
  ignored:
    urls:
      - /admin/*
      - /admin/test
      #      - /admin/hello
      - /admin/getUser/*
      - /admin/register
      - /admin/login
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer'  #JWT负载中拿到开头


logging:
  level:
    #    org.springframework: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.cache: TRACE
    org.springframework.data.redis: TRACE

#    com.nimbusds: TRACE
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
    - classpath:mapper/*.xml

