spring:
  profiles:
    active: common, mbg,secure

  redis:
    database: ${redisConf.mallDev}
    host: 192.168.11.8
    port: 6379
    connect-timeout: 5000
  cache:
    redis:
      time-to-live: 3d
      use-key-prefix: true
  data:
    mongodb:
      uri:  mongodb://root:example@192.168.11.8:27017/
      username: root
      password: example
      database: mall

redisConf:
  mallDev: 0

#mybatis-plus:
#  mapper-locations: classpath*:mapper/*.xml
secure:
  ignored:
    urls:
      - /admin/*
      - /admin/test
      #      - /admin/hello
      - /admin/getUser/*
      - /admin/register
      - /admin/login
      - /role/**
      - /actuator/**
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer'  #JWT负载中拿到开头


logging:
  level:
    #    org.springframework: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.cache: TRACE
    org.springframework.data.redis: TRACE

#    com.nimbusds: TRACE


