spring:
  autoconfigure:
    #自动化配置 例外处理
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://192.168.11.8:3306/mall
          username: root
          password: root
      #          driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
      #        slave_1:
      #          url: jdbc:mysql://192.168.11.8:3306/mall
      #          username: root
      #          password: root
      #          driver-class-name: com.mysql.jdbc.Driver
      #        slave_2:
      #          url: ENC(xxxxx) # 内置加密,使用请查看详细文档
      #          username: ENC(xxxxx)
      #          password: ENC(xxxxx)
      #          driver-class-name: com.mysql.jdbc.Driver
      druid:
        initialSize: 5
        minIdle: 5
        maxActive: 30
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j,config
        useGlobalDataSourceStat: true
        stat:
          log-slow-sql: true
          merge-sql: true
          slow-sql-millis: 10000

  redis:
    database: ${redisConf.mallDev}
    host: 192.168.11.8
    port: 6379
    connect-timeout: 5000
  cache:
    redis:
      time-to-live: 3d
      use-key-prefix: true
  data:
    mongodb:
      uri:  mongodb://root:example@192.168.11.8:27017/
      username: root
      password: example
      database: mall

redisConf:
  mallDev: 0

secure:
  ignored:
    urls:
      - /test/**
      - /admin/**
      - /admin/test
      #      - /admin/hello
      - /admin/getUser/*
      - /admin/register
      - /admin/login
      - /role/**
      - /actuator/**
      - /druid/**
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: mall-admin-secret #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer'  #JWT负载中拿到开头


logging:
  level:
    #    org.springframework: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.cache: TRACE
    org.springframework.data.redis: TRACE

#    com.nimbusds: TRACE
mybatis-plus:
  mapper-locations:
    - classpath*:mapper/**/*.xml
    - classpath*:mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  show-actuator: true
  use-management-port: true
# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
management:
  server:
    port: 9990
  endpoints:
    web:
      exposure:
        include: openapi, swagger-ui

druid-monitor:
  web: "on"