#spring:
#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:myapp
#    username: sa
#    password:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    generate-ddl: true

spring:
  datasource:
    url: jdbc:mysql://root:root@192.168.11.8:3306/learn-spring-jpa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true

