spring:
  profiles:
    active: dev
---
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:myapp
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    generate-ddl: true
  redis:
    database: 1
    host: 192.168.11.8
    password:
    port: 6379
    client-type: lettuce
  config:
    activate:
      on-profile: test

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


---
spring:
  datasource:
    url: jdbc:mysql://root:root@192.168.11.8:3306/learn-spring-jpa
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    #    show-sql: true
    generate-ddl: true
  redis:
    database: 0
    host: 192.168.11.8
    password:
    port: 6379
  config:
    activate:
      on-profile: dev

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

