###
POST http://localhost:8080/admin/register
Content-Type: application/json

{
  "username": "fuxyifuck1d2",
  "password": "test",
  "icon": "http://localhost:8080/icon/test.png",
  "email": "1233@gg.com",
  "nickName": "sillytest",
  "note": "this is a note"
}

###
POST http://localhost:8080/admin/login
Content-Type: application/json

{
  "username": "fuxyifuck",
  "password": "test"
}

###
GET http://localhost:8080/admin/hello
Bearer: eyJraWQiOiJtYWxsLWFkbWluLXNlY3JldCIsInR5cCI6IkpXVCIsImFsZyI6IkVkRFNBIn0.eyJzdWIiOiJmdXh5aWZ1Y2siLCJleHAiOjE2NjE1NjQ0MzcsImNyZWF0ZWQiOiIyMDIyLTA4LTIwIn0.fZCMYdkqPJhlYhQIEacrSjDm2jILAa8nkdxOv1GouoefLSCn385of13FFY6ozA_fBz-YagAgXQsYDvYUoJgACA

###
GET http://localhost:8080/admin/test
Bearer: eyJraWQiOiJtYWxsLWFkbWluLXNlY3JldCIsInR5cCI6IkpXVCIsImFsZyI6IkVkRFNBIn0.eyJzdWIiOiJmdXh5aWZ1Y2siLCJleHAiOjE2NjE1NjQ0MzcsImNyZWF0ZWQiOiIyMDIyLTA4LTIwIn0.fZCMYdkqPJhlYhQIEacrSjDm2jILAa8nkdxOv1GouoefLSCn385of13FFY6ozA_fBz-YagAgXQsYDvYUoJgACA
