###
POST http://localhost:8080/admin/register
Content-Type: application/json

{
  "username": "fuxyifuck",
  "password": "test",
  "icon": "http://localhost:8080/icon/test.png",
  "email": "1233@gg.com",
  "nickName": "sillytest",
  "note": "this is a note"
}

###
GET http://localhost:8080/admin/hello
