name: workflow example

# on: [push]
on:
  workflow_call:

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      # - name: checkout
      #   uses: actions/checkout@v2
      #   with:
      #     ref: "reuse-workflow-A"
      - name: Hello world action step
        uses: leavyli/Brick-Works@reuse-workflow-A
        id: hello
        with:
          who-to-greet: "Mona the Octocat"

      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

        # with:
        #   username: ${{ inputs.username }}
        #   token: ${{ secrets.token }}
